Reporting scroll lag
KoddiDev/ReportTable pull request #1
Opened 2016-12-12 19:12 UTC by bkovacik

Closes #6736.

I added a scroll method to a new default container. It falls back to the previous behavior if one is not provided, so it shouldn't break any other code that relies on this.

Also softened tabs.

2016-12-12 19:27 UTC, kyrozetera requested changes
Just a couple of small things, otherwise looks good.

2016-12-12 19:27 UTC, kyrozetera commented on dist/reporttable.js
> +        console.log(this.options.scrollDefaultObject);
A couple of `console.log`s got left behind.

2016-12-12 19:27 UTC, kyrozetera commented on dist/reporttable.js
> +        scrollDefaultObject:null
Should we name this option `scrollEventObject`, or something, so the purpose is clearer from the name?

2016-12-12 19:28 UTC, peterbrescia commented
Not sure how original minification was achieved, but we should probably figure out how and update the min.js and map files too.

2016-12-12 19:35 UTC, kyrozetera commented
@peterbrescia Good catch. We don't currently use the `min` file, but we could swap that out in Koddi also.

2017-01-16 17:20 UTC, peterbrescia commented
Would be good to get this out. Looks like review has been addressed?

2017-01-16 17:39 UTC, kyrozetera approved these changes

2017-01-16 17:40 UTC, peterbrescia approved these changes

2017-01-16 17:40 UTC, kyrozetera commented
@peterbrescia Yes, we can merge this one now, and we'll need to create a PR to update to this repo in koddi.

2017-01-16 17:40 UTC, merged